# --------------------------------------------------
# CONEXIÓN A BASE DE DATOS
# --------------------------------------------------

# 'supabase' -> Utiliza Supabase
# 'h2' -> Utiliza H2
# 'docker' -> Utiliza Docker (PostgreSQL + Mailpit)
spring.profiles.active=h2

spring.application.name=erp
server.port=${PORT:8080}

# --------------------------------------------------
# SEGURIDAD Y GESTIÓN DE SESIONES (JSESSIONID)
# --------------------------------------------------
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=30m
