# --------------------------------------------------
# CONEXIÓN A BASE DE DATOS (SUPABASE - POSTGRESQL)
# --------------------------------------------------

# URL JDBC oficial para PostgreSQL con SSL obligatorio (compatible con Connection Pooler IPv4)
spring.datasource.url=jdbc:postgresql://${DB_HOST_SUPABASE}:${DB_PORT_SUPABASE:5432}/${DB_DATABASE_SUPABASE:postgres}?sslmode=require

# Credenciales de conexion a Supabase
spring.datasource.username=${DB_USERNAME_SUPABASE}
spring.datasource.password=${DB_PASSWORD_SUPABASE}

# El driver obligatorio de Java para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------------------------------
# CONFIGURACIÓN DE JPA / HIBERNATE
# ------------------------------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect