# --------------------------------------------------
# CONEXIÓN A BASE DE DATOS
# --------------------------------------------------

# 'supabase' -> Utiliza Supabase
# 'h2' -> Utiliza H2
# 'docker' -> Utiliza Docker (PostgreSQL + Mailpit)
spring.profiles.active=h2

spring.application.name=erp
server.port=${PORT:8080}